package livrarianavegador;

import daolivraria.*;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

public class JanelaPrincipal extends javax.swing.JFrame {

    private LivroDAO livrosdao;
    private ArrayList <LivroTO> livros;
    private int index;
    
    public JanelaPrincipal() {
        index = 0;
        livrosdao = new LivroDAO();
        livros = livrosdao.listAll();
        initComponents();
        /*try{
            panel_Capa.add(new JLabel(new ImageIcon(livrosdao.getCapaImage(index+1))));
        }catch(NullPointerException e)
        {
            System.out.println(e.getMessage());
        }*/
        panel_Capa.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_NomeLivro = new javax.swing.JLabel();
        textbox_NomeLivro = new javax.swing.JTextField();
        textbox_IDLivro = new javax.swing.JTextField();
        label_IDLivro = new javax.swing.JLabel();
        button_Primeiro = new javax.swing.JButton();
        button_Anterior = new javax.swing.JButton();
        button_Proximo = new javax.swing.JButton();
        button_Ultimo = new javax.swing.JButton();
        button_Procurar = new javax.swing.JButton();
        textbox_Procurar = new javax.swing.JTextField();
        scrollpanel_DadosLivro = new javax.swing.JScrollPane();
        panel_DadosLivro = new javax.swing.JPanel();
        panel_Capa = new javax.swing.JPanel();
        panel_Livros = new javax.swing.JPanel();
        separator_NomeDadosSeparador = new javax.swing.JSeparator();
        label_Autor = new javax.swing.JLabel();
        label_Editora = new javax.swing.JLabel();
        label_Ano = new javax.swing.JLabel();
        label_Genero = new javax.swing.JLabel();
        label_Preco = new javax.swing.JLabel();
        label_Quantidade = new javax.swing.JLabel();
        label_Reservados = new javax.swing.JLabel();
        textbox_Autor = new javax.swing.JTextField();
        textbox_Editora = new javax.swing.JTextField();
        textbox_Ano = new javax.swing.JTextField();
        textbox_Genero = new javax.swing.JTextField();
        textbox_Preco = new javax.swing.JTextField();
        textbox_Quantidade = new javax.swing.JTextField();
        textbox_Reservados = new javax.swing.JTextField();
        scrollpanel_Descricao = new javax.swing.JScrollPane();
        textarea_Descricao = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(680, 370));
        setPreferredSize(new java.awt.Dimension(680, 370));

        label_NomeLivro.setText("Livro:");

        textbox_NomeLivro.setEditable(false);
        textbox_NomeLivro.setText(livros.get(index).getTitulo()
        );

        textbox_IDLivro.setEditable(false);
        textbox_IDLivro.setText(Integer.toString(livros.get(index).getLivro_id())
        );

        label_IDLivro.setText("ID:");

        button_Primeiro.setText("Primeiro");
        button_Primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_PrimeiroActionPerformed(evt);
            }
        });

        button_Anterior.setText("Anterior");
        button_Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_AnteriorActionPerformed(evt);
            }
        });

        button_Proximo.setText("Próximo");
        button_Proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ProximoActionPerformed(evt);
            }
        });

        button_Ultimo.setText("Último");
        button_Ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_UltimoActionPerformed(evt);
            }
        });

        button_Procurar.setText("Procurar");
        button_Procurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ProcurarActionPerformed(evt);
            }
        });

        textbox_Procurar.setText("Procurar...");
        textbox_Procurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textbox_ProcurarActionPerformed(evt);
            }
        });

        panel_DadosLivro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        panel_Capa.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout panel_CapaLayout = new javax.swing.GroupLayout(panel_Capa);
        panel_Capa.setLayout(panel_CapaLayout);
        panel_CapaLayout.setHorizontalGroup(
            panel_CapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
        );
        panel_CapaLayout.setVerticalGroup(
            panel_CapaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel_Livros.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        separator_NomeDadosSeparador.setOrientation(javax.swing.SwingConstants.VERTICAL);

        label_Autor.setText("Autor:");

        label_Editora.setText("Editora:");

        label_Ano.setText("Ano:");

        label_Genero.setText("Gênero:");

        label_Preco.setText("Preço:");

        label_Quantidade.setText("Quantidade:");

        label_Reservados.setText("Reservados:");

        textbox_Autor.setEditable(false);
        textbox_Autor.setText(livros.get(index).getAutor());

        textbox_Editora.setEditable(false);
        textbox_Editora.setText(livros.get(index).getEditora());

        textbox_Ano.setEditable(false);
        textbox_Ano.setText(Integer.toString(livros.get(index).getAno()));

        textbox_Genero.setEditable(false);
        textbox_Genero.setText(livros.get(index).getGenero()
        );

        textbox_Preco.setEditable(false);
        textbox_Preco.setText(String.format("R$ %.2f",livros.get(index).getPreco()));

        textbox_Quantidade.setEditable(false);
        textbox_Quantidade.setText(Integer.toString(livros.get(index).getEstoque())
        );

        textbox_Reservados.setEditable(false);
        textbox_Reservados.setText(Integer.toString(livros.get(index).getReserva()));

        javax.swing.GroupLayout panel_LivrosLayout = new javax.swing.GroupLayout(panel_Livros);
        panel_Livros.setLayout(panel_LivrosLayout);
        panel_LivrosLayout.setHorizontalGroup(
            panel_LivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_LivrosLayout.createSequentialGroup()
                .addGroup(panel_LivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_LivrosLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(panel_LivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_Autor)
                            .addComponent(label_Editora)
                            .addComponent(label_Ano)
                            .addComponent(label_Preco)
                            .addComponent(label_Quantidade)
                            .addComponent(label_Genero)))
                    .addGroup(panel_LivrosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_Reservados)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separator_NomeDadosSeparador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_LivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textbox_Autor, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(textbox_Ano)
                    .addComponent(textbox_Editora, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textbox_Preco)
                    .addComponent(textbox_Genero, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(textbox_Reservados)
                    .addComponent(textbox_Quantidade, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        panel_LivrosLayout.setVerticalGroup(
            panel_LivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separator_NomeDadosSeparador)
            .addGroup(panel_LivrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_LivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(textbox_Autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_Autor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_LivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(label_Editora)
                    .addComponent(textbox_Editora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_LivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(label_Ano)
                    .addComponent(textbox_Ano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_LivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(label_Genero)
                    .addComponent(textbox_Genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_LivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(label_Preco)
                    .addComponent(textbox_Preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_LivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(label_Quantidade)
                    .addComponent(textbox_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_LivrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(label_Reservados)
                    .addComponent(textbox_Reservados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        textarea_Descricao.setEditable(false);
        textarea_Descricao.setColumns(20);
        textarea_Descricao.setRows(5);
        textarea_Descricao.setTabSize(0);
        textarea_Descricao.setText(livros.get(index).getDescricao());
        scrollpanel_Descricao.setViewportView(textarea_Descricao);

        javax.swing.GroupLayout panel_DadosLivroLayout = new javax.swing.GroupLayout(panel_DadosLivro);
        panel_DadosLivro.setLayout(panel_DadosLivroLayout);
        panel_DadosLivroLayout.setHorizontalGroup(
            panel_DadosLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_DadosLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_DadosLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollpanel_Descricao)
                    .addGroup(panel_DadosLivroLayout.createSequentialGroup()
                        .addComponent(panel_Livros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panel_Capa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panel_DadosLivroLayout.setVerticalGroup(
            panel_DadosLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_DadosLivroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_DadosLivroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel_Livros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_Capa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollpanel_Descricao)
                .addContainerGap())
        );

        scrollpanel_DadosLivro.setViewportView(panel_DadosLivro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(button_Primeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_Anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(button_Procurar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textbox_Procurar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_Proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_Ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(label_NomeLivro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textbox_NomeLivro)
                        .addGap(26, 26, 26)
                        .addComponent(label_IDLivro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textbox_IDLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrollpanel_DadosLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_NomeLivro)
                    .addComponent(textbox_NomeLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textbox_IDLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_IDLivro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollpanel_DadosLivro, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_Primeiro)
                    .addComponent(button_Anterior)
                    .addComponent(textbox_Procurar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_Proximo)
                    .addComponent(button_Ultimo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_Procurar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_UltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_UltimoActionPerformed
        index = livros.size()-1;
        updateBoxes();
    }//GEN-LAST:event_button_UltimoActionPerformed

    private void textbox_ProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textbox_ProcurarActionPerformed
        button_ProcurarActionPerformed(evt);
    }//GEN-LAST:event_textbox_ProcurarActionPerformed

    private void button_ProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ProcurarActionPerformed
        String pesquisa = textbox_Procurar.getText();
        for(LivroTO livro: livros)
        {
            if(livro.getTitulo().equals(pesquisa))
            {
                JanelaTabela janTab = new JanelaTabela(livro);
                janTab.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                janTab.setVisible(true);
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "Livro \""+pesquisa+"\" não encontrado.");
    }//GEN-LAST:event_button_ProcurarActionPerformed

    private void button_PrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_PrimeiroActionPerformed
        index = 0;
        updateBoxes();
    }//GEN-LAST:event_button_PrimeiroActionPerformed

    private void button_AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_AnteriorActionPerformed
        if(index > 0)
            index--;
        updateBoxes();
    }//GEN-LAST:event_button_AnteriorActionPerformed

    private void button_ProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ProximoActionPerformed
        if(index < livros.size()-1)
            index++;
        updateBoxes();
    }//GEN-LAST:event_button_ProximoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }
    
    private void updateBoxes()
    {
    textbox_Ano.setText(Integer.toString(livros.get(index).getAno()));
    textbox_Autor.setText(livros.get(index).getAutor());
    textbox_Editora.setText(livros.get(index).getEditora());
    textbox_Genero.setText(livros.get(index).getGenero());
    textbox_IDLivro.setText(Integer.toString(livros.get(index).getLivro_id()));
    textbox_NomeLivro.setText(livros.get(index).getTitulo());
    textbox_Preco.setText(String.format("R$ %.2f", livros.get(index).getPreco()));
    textbox_Quantidade.setText(Integer.toString(livros.get(index).getEstoque()));
    textbox_Reservados.setText(Integer.toString(livros.get(index).getReserva()));
    textarea_Descricao.setText(livros.get(index).getDescricao());
    }
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Anterior;
    private javax.swing.JButton button_Primeiro;
    private javax.swing.JButton button_Procurar;
    private javax.swing.JButton button_Proximo;
    private javax.swing.JButton button_Ultimo;
    private javax.swing.JLabel label_Ano;
    private javax.swing.JLabel label_Autor;
    private javax.swing.JLabel label_Editora;
    private javax.swing.JLabel label_Genero;
    private javax.swing.JLabel label_IDLivro;
    private javax.swing.JLabel label_NomeLivro;
    private javax.swing.JLabel label_Preco;
    private javax.swing.JLabel label_Quantidade;
    private javax.swing.JLabel label_Reservados;
    private javax.swing.JPanel panel_Capa;
    private javax.swing.JPanel panel_DadosLivro;
    private javax.swing.JPanel panel_Livros;
    private javax.swing.JScrollPane scrollpanel_DadosLivro;
    private javax.swing.JScrollPane scrollpanel_Descricao;
    private javax.swing.JSeparator separator_NomeDadosSeparador;
    private javax.swing.JTextArea textarea_Descricao;
    private javax.swing.JTextField textbox_Ano;
    private javax.swing.JTextField textbox_Autor;
    private javax.swing.JTextField textbox_Editora;
    private javax.swing.JTextField textbox_Genero;
    private javax.swing.JTextField textbox_IDLivro;
    private javax.swing.JTextField textbox_NomeLivro;
    private javax.swing.JTextField textbox_Preco;
    private javax.swing.JTextField textbox_Procurar;
    private javax.swing.JTextField textbox_Quantidade;
    private javax.swing.JTextField textbox_Reservados;
    // End of variables declaration//GEN-END:variables
}
